services:

  airflow:
    image: apache/airflow:2.8.1-python3.9
    container_name: airflow
    env_file:
      - .env.dev
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW_CORE_LOAD_EXAMPLES: "false"
      AIRFLOW_CORE_FERNET_KEY: "assignmentkey0000"
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow scheduler &
        airflow webserver"

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env.dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: