services:

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data

  fastapi:
    build: ./app
    container_name: fastapi_rag
    ports:
      - "8500:8500"
    env_file:
      - .env.dev
    depends_on:
      - chroma

  airflow:
    image: apache/airflow:2.9.3-python3.10
    container_name: airflow
    env_file:
      - .env.dev
    volumes:
      - ./airflow:/opt/airflow
      - ./code:/opt/airflow/code
      - ./utils:/opt/airflow/utils
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install -r /requirements.txt  --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.10.txt" &&
      airflow db migrate &&
        airflow scheduler &
        airflow webserver"

  minio:
    image: minio/minio:latest
    container_name: minio
    env_file:
      - .env.dev
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
  postgres_data:
  chroma_data: